FROM python:3.12-slim-trixie

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

RUN uv venv

RUN uv pip install -U fastmcp dotenv requests ollama chromadb

COPY . /app

WORKDIR /app

EXPOSE 7777

CMD ["uv","run","docker_server.py","--host","0.0.0.0","--port","6969"]